spring:
  application:
    name: Hdu-Passbook
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  kafka:
    bootstrap-servers:  127.0.01:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8080

logging:
  file: hdu-passbook.log
  level:
    root: info


